USE practice1and2;
SHOW TABLES;
DESCRIBE DEPT;
SELECT * FROM DEPT;
DESCRIBE EMP;
SELECT EMPNO, ENAME, JOB,JOB, MGR, SAL, COMM, DEPTNO, HIREDATE
STARTDATE
FROM emp
ORDER BY(ENAME);
SELECT DISTINCT JOB 
FROM EMP;

ALTER TABLE EMP
CHANGE COLUMN EMPNO  EMP INT(7) ;
ALTER TABLE EMP
CHANGE COLUMN ENAME EMPLOYEE VARCHAR(25);
ALTER TABLE EMP
CHANGE COLUMN JOB  JOB_TITLE VARCHAR(25) ;
ALTER TABLE EMP
CHANGE COLUMN HIREDATE  HIRE_DATE DATE;

DESC EMP;
SELECT EMPLOYEE, SAL 
FROM EMP
WHERE SAL > 2000;

SELECT EMPLOYEE, DEPTNO 
FROM EMP
WHERE EMP= 7902;

SELECT EMPLOYEE, SAL 
FROM EMP
WHERE SAL BETWEEN 2000 AND 5000;

SELECT EMPLOYEE, JOB_TITLE, HIRE_DATE 
FROM EMP
WHERE HIRE_DATE BETWEEN 20-02-81 AND 1-05-81;

SELECT EMPLOYEE, DEPTNO 
FROM EMP
WHERE DEPTNO BETWEEN 10 AND 30 
ORDER BY EMPLOYEE ASC;

SELECT EMPLOYEE "Employee", SAL "Monthly Salary"
FROM EMP 
WHERE (SAL BETWEEN 2000 AND 3000) AND DEPTNO IN (10,30);

SELECT EMPLOYEE, HIRE_DATE
FROM EMP
WHERE HIRE_DATE LIKE '%81';

SELECT EMPLOYEE, JOB_TITLE
FROM EMP
WHERE MGR IS NULL;

DESC EMP;

SELECT EMPLOYEE, SAL, COMM 
FROM EMP
WHERE COMM IS NOT NULL
ORDER BY SAL,COMM;

SELECT EMPLOYEE
FROM EMP
WHERE EMPLOYEE LIKE '__a%';

SELECT EMPLOYEE
FROM EMP
WHERE EMPLOYEE LIKE 'a%'
AND EMPLOYEE LIKE 'e%';

SELECT EMPLOYEE,JOB_TITLE,SAL
FROM EMP
WHERE (JOB_TITLE = 'salesman' OR JOB_TITLE = 'clerk')
AND SAL NOT IN (1600,8000,1300);

SELECT EMPLOYEE,COMM,SAL
FROM EMP
WHERE COMM = .2;

-- PRACTICE 3

SELECT ROUND (MAX(SAL),0) "MAXIMUM",
ROUND (MIN(SAL),0) "MINIMUM",
ROUND (SUM(SAL),0) "SUM",
ROUND (AVG(SAL),0) "AVERAGE"
FROM EMP;

SELECT JOB_TITLE, ROUND (MAX(SAL),0) "MAXIMUM",
ROUND (MIN(SAL),0) "MINIMUM",
ROUND (SUM(SAL),0) "SUM",
ROUND (AVG(SAL),0) "AVERAGE"
FROM EMP
GROUP BY JOB_TITLE;

SELECT JOB_TITLE, COUNT(*)
FROM EMP
GROUP BY JOB_TITLE;

SELECT COUNT(DISTINCT MGR) "NUMBER OF MANAGERS"
FROM EMP; 

SELECT MAX(SAL) - MIN(SAL) DIFFERENCE
FROM EMP;

SELECT MGR, MIN(SAL)
FROM EMP
WHERE  MGR IS NOT NULL
GROUP BY MGR
HAVING MIN(SAL) > 1000
ORDER BY MIN(SAL) DESC;

-- PRACTICE 4

SELECT EMPLOYEE, HIRE_DATE
FROM EMP
WHERE DEPTNO =
( SELECT DEPTNO
FROM EMP
WHERE EMPLOYEE = 'SMITH')
AND EMPLOYEE <> 'SMITH';

SELECT EMP,EMPLOYEE
FROM EMP
WHERE SAL > 
(SELECT AVG(SAL)
FROM EMP)
ORDER BY SAL;

SELECT EMP,EMPLOYEE
FROM EMP
WHERE DEPTNO IN
(SELECT DEPTNO 
FROM EMP WHERE EMPLOYEE LIKE '%U');

SELECT EMPLOYEE, SAL
FROM EMP
WHERE MGR =
(SELECT EMPLOYEE 
FROM EMP
WHERE EMPLOYEE = 'BLAKE');

SELECT EMPLOYEE, JOB_TITLE, DEPTNO
FROM EMP
WHERE JOB_TITLE IN 
(SELECT JOB_TITLE
FROM EMP
WHERE JOB_TITLE = 'SALES');


